RazorPagesPersonRegistry/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesPersonRegistry.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesPersonRegistry/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesPersonRegistry.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorPagesPersonRegistry/Pages/PersonAddressInformation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonRegistryLibrary.Interfaces;
using PersonRegistryLibrary.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace RazorPagesPersonRegistry.Pages
{
    public class PersonAddressInformationModel : PageModel
    {
        readonly IDataAccess<PersonModel> _personSessionStorage;
        readonly IDataAccess<AddressModel> _addressSessionStorage;

        public PersonAddressInformationModel(IDataAccess<PersonModel> personSessionStorage, IDataAccess<AddressModel> addressSessionStorage)
        {
            _personSessionStorage = personSessionStorage;
            _addressSessionStorage = addressSessionStorage;
        }

        [BindProperty]
        public PersonModel Person { get; set; }

        [BindProperty]
        public List<AddressModel> Addresses { get; set; } = new List<AddressModel>();

        [BindProperty]
        public string City { get; set; }

        [BindProperty]
        public string Street { get; set; }

        [BindProperty]
        public string PostalCode { get; set; }

        public void OnGet()
        {
        }

        public void OnGetPersonDetails(string firstName, string lastName, int age, int? id = null)
        {
            Person = new PersonModel { FirstName = firstName, LastName = lastName, Age = age, Id = id };
            if (Person.Id != null)
            {
                Addresses = _addressSessionStorage.GetAll().Where(x => x.PersonId == Person.Id).ToList();
            }
        }

        public void OnPostAddAddress()
        {
            Addresses.Add(new AddressModel { City = City, Street = Street, PostalCode = PostalCode });
        }

        public IActionResult OnPostAddPerson()
        {
            _personSessionStorage.Add(Person);

            foreach (var address in Addresses)
            {
                address.PersonId = Person.Id;
                _addressSessionStorage.Add(address);
            }

            Addresses = _addressSessionStorage.GetAll().ToList();
            return RedirectToPage("PersonList");
        }
    }
}

RazorPagesPersonRegistry/Pages/PersonGeneralInformation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonRegistryLibrary.Interfaces;
using PersonRegistryLibrary.Models;
using System.Collections.ObjectModel;

namespace RazorPagesPersonRegistry.Pages
{
    public class PersonGeneralInformationModel : PageModel
    {
        readonly IDataAccess<PersonModel> _personSessionStorage;
        private ReadOnlyCollection<PersonModel> _persons;

        readonly IDataAccess<AddressModel> _addressSessionStorage;
        private ReadOnlyCollection<AddressModel> _addresses;

        [BindProperty]
        public string FirstName { get; set; }

        [BindProperty]
        public string LastName { get; set; }

        [BindProperty]
        public int Age { get; set; }

        [BindProperty]
        public int? Id { get; set; }

        public void OnGet()
        {
        }

        public void OnGetEditPerson(string firstName, string lastName, int age, int id)
        {
            FirstName = firstName;
            LastName = lastName;
            Age = age;
            Id = id;
        }

        public IActionResult OnPost()
        {
            if (Id == null)
            {
                return RedirectToPage("PersonAddressInformation", "PersonDetails", new { firstName = FirstName, lastName = LastName, age = Age});
            }
            else
            {
                return RedirectToPage("PersonAddressInformation", "PersonDetails", new { firstName = FirstName, lastName = LastName, age = Age, id = Id});
            }
            
        }
    }
}

RazorPagesPersonRegistry/Pages/PersonList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonRegistryLibrary.Interfaces;
using PersonRegistryLibrary.Models;
using PersonRegistryLibrary.Services;
using System.Collections.ObjectModel;

namespace RazorPagesPersonRegistry.Pages
{
    public class PersonListModel : PageModel
    {
        readonly IDataAccess<PersonModel> _personSessionStorage;
        private ReadOnlyCollection<PersonModel> _persons;

        public PersonListModel(IDataAccess<PersonModel> personSessionStorage)
        {
            _personSessionStorage = personSessionStorage;
        }

        public ReadOnlyCollection<PersonModel> Persons => _persons;

        public void OnGet()
        {
            _persons = _personSessionStorage.GetAll();
        }

        public IActionResult OnPost()
        {
            return RedirectToPage("PersonGeneralInformation");
        }



    }
}

RazorPagesPersonRegistry/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesPersonRegistry.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesPersonRegistry/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorPagesPersonRegistry/Pages/PersonAddressInformation.cshtml
@page
@model RazorPagesPersonRegistry.Pages.PersonAddressInformationModel
@{
}

<form method="post" id="addressForm" asp-page-handler="AddAddress">
    <input type="hidden" asp-for="Person.FirstName" />
    <input type="hidden" asp-for="Person.LastName" />
    <input type="hidden" asp-for="Person.Age" />
    <input type="hidden" asp-for="Person.Id" />
    
    @for(int i = 0; i < Model.Addresses.Count; i++ )
    {
        <input type="hidden" asp-for="Addresses[i].City" />
        <input type="hidden" asp-for="Addresses[i].Street" />
        <input type="hidden" asp-for="Addresses[i].PostalCode" />
    }

    <label asp-for="City">City</label><br />
    <input type="text" asp-for="City" /><br /><br />
    <label asp-for="Street">Street</label><br />
    <input type="text" asp-for="Street" /><br /><br />
    <label asp-for="PostalCode">Postal Code</label><br />
    <input type="text" asp-for="PostalCode" /><br /><br />
    <button class="btn btn-secondary" type="submit" form="addressForm">Add adress</button>
    <button class="btn btn-primary" type="submit" form="personForm">Save Person</button>
</form>
<br />
@foreach(var addresses in Model.Addresses)
{
    <a class="page-link">@addresses.DisplayName</a>
}
<form id="personForm" asp-page-handler="AddPerson">
    @for (int i = 0; i < Model.Addresses.Count; i++)
    {
        <input type="hidden" asp-for="Addresses[i].City" />
        <input type="hidden" asp-for="Addresses[i].Street" />
        <input type="hidden" asp-for="Addresses[i].PostalCode" />
    }

    <input type="hidden" asp-for="Person.FirstName" />
    <input type="hidden" asp-for="Person.LastName" />
    <input type="hidden" asp-for="Person.Age" />
    <input type="hidden" asp-for="Person.Id" />
</form>

RazorPagesPersonRegistry/Pages/PersonGeneralInformation.cshtml
@page
@model RazorPagesPersonRegistry.Pages.PersonGeneralInformationModel
@{
}

<form asp-page-handler="" method="post">
    <label asp-for="FirstName">First Name</label><br />
    <input type="text" asp-for="FirstName" /><br /><br />
    <label asp-for="LastName">Last Name</label><br />
    <input type="text" asp-for="LastName" /><br /><br />
    <label asp-for="Age">Age</label><br />
    <input type="text" asp-for="Age" /><br /><br />
    <input type="hidden" asp-for="Id" />
    <button class="btn btn-primary" type="submit">Next</button>
</form>

RazorPagesPersonRegistry/Pages/PersonList.cshtml
@page
@model RazorPagesPersonRegistry.Pages.PersonListModel
@{
}

<h2>Person Registry</h2>

<br />
<form method="post">
    <button class="btn btn-primary" type="submit">Add person</button>
</form>
<br />
<h4>Person list:</h4>
@foreach (var person in Model.Persons)
{
    <a asp-page="PersonGeneralInformation" asp-page-handler="EditPerson" asp-route-firstname="@person.FirstName" asp-route-lastname="@person.LastName" asp-route-age="@person.Age" asp-route-id="@person.Id" class="page-link">@person.DisplayName</a>
}

RazorPagesPersonRegistry/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesPersonRegistry</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPagesPersonRegistry</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/PersonList">Person Registry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RazorPagesPersonRegistry - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>